import "./globals.css";
import { PropsWithChildren } from "react";
import ChakraUIProvider from "@/components/providers/ChakraProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="ko">
      <body suppressContentEditableWarning suppressHydrationWarning>
        <ChakraUIProvider>{children}</ChakraUIProvider>
      </body>
    </html>
  );
}
